config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: 'users/sessions', 
                                   passwords: 'users/passwords',
                                   registrations: 'users/registrations'}

  resources :companies do
    resources :products
  end

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :products, dependent: :delete_all
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :company

  #has_attached_file :photo, styles: {medium: "200x200>", thumb: "50x50>"}, url: "/:class/:attachment/:id/:style_:filename", default_url: "default/default_:style_photo.jpg"
  #validates_attachment :photo, content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) }

  mount_uploader :picture, PictureUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def render_404
      render file: "public/404.html", status: 404
    end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_filter :find_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @companies = Company.all.order("id").page(params[:page]).per_page(10)
  end

  def show
    @products = @company.products.order("id").page(params[:page]).per_page(20)
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.create(company_params)
    redirect_to company_path(@company)
  end

  def update
    @company.update(company_params)
    if @company.errors.empty?
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to action: :index
  end

  private

    def company_params
      params.require(:company).permit(:name, :description, :foundation)
    end

    def find_company
      @company = Company.find(params[:id])
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @company = Company.find(params[:company_id])
    @products = Product.where(company_id: params[:company_id]).order("id").page(params[:page]).per_page(20)
    render_404
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.create(product_params)
    redirect_to company_product_path(params[:company_id], @product)
  end

  def update
    @product.update(product_params)
    if @product.errors.empty?
      redirect_to company_product_path(params[:company_id], @product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to company_path(params[:company_id])
  end

  private

    def product_params
      params.require(:product).permit(:name, :description, :price, :company_id, :photo, :picture)
    end

    def find_product
      @product = Product.find(params[:id])
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/companies/edit.html.haml
.container
  .row
    .col-xs-offset-4.col-xs-4
      %h1.form-name Edit this company
      =form_for @company do |f|
        .form-group
          %label Company name:
          =f.text_field :name, class: "form-control"
        .from-group
          %label Company description:
          =f.text_area  :description, class: "form-control"
        .form-group
          %label Since:
          =f.text_field :foundation, class: "form-control"
        =f.submit 'Save', class: "btn btn-primary"
        = link_to "Cancel",  company_path(@company), class: "btn btn-danger"

app/views/companies/index.html.haml
.center
  %h1 All companies
  %h4= link_to "one more?", new_company_path
- if @companies.empty?
  %p No companies in system.
- else
  .container
    .row
      %table.table.table-striped.col-xs-10  
        %tr
          %th ID
          %th Name
          %th Since
          %th Description
        - @companies.each do |c|
          %tr
            %td= c.id
            %td= link_to c.name, company_path(c)
            %td= c.foundation
            %td= c.description
    .row
      .center= will_paginate @companies, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 1

app/views/companies/new.html.haml
.container
  .row
    .col-xs-offset-4.col-xs-4
      %h1.form-name Create new company
      =form_for @company do |f|
        .form-group
          %label Company name:
          = f.text_field :name, class: "form-control"
        .form-group
          %label Since:
          = f.text_field :foundation, class: "form-control"
        .form-group
          %label Company description:
          = f.text_area  :description, class: "form-control"
        = f.submit "Save", class: "btn btn-primary"
        = link_to "Cancel",  companies_path, class: "btn btn-danger"

app/views/companies/show.html.haml
.container
  .row
    %blockquote
      %h1= @company.name
      %h3= "ID: #{@company.id}"
      %h3= "Since: #{@company.foundation}"
      %h3= "Description: #{@company.description}"
    .btn-group
      = link_to "Edit company", edit_company_path(@company), class: "btn btn-default"
      = link_to "Delete company", company_path(@company), method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-default"
      = link_to "Go to all companies", companies_path, class: "btn btn-default"
      = link_to "Add new product", new_company_product_path(@company), class: "btn btn-default"

= render template: "products/index"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyLearning</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert%>
  <p class="alert"><%= alert %></p>
<%end%>

<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "logout" %>

<%= yield %>

</body>
</html>

app/views/products/edit.html.haml
.container
  .row
    .col-xs-offset-4.col-xs-4
      %h1.form-name Edit this product
      =form_for @product, url: company_product_path do |f|
        .form-group
          %label Product name:
          =f.text_field :name, class: "form-control"
        .form-group
          %label Product description:
          =f.text_area  :description, class: "form-control"
        .form-group
          %label Price:
          =f.text_field :price, class: "form-control"
        .form-group
          %label Photo
          %br= image_tag @product.picture_url, class: "img-thumbnail" if @product.picture?
          = f.file_field :picture
        = f.submit 'Save', class: "btn btn-primary"
        = link_to "Cancel",  company_product_path, class: "btn btn-danger"

app/views/products/index.html.haml
- if @products.empty?
  %p No products for this company.
- else
  .container
    .row
      %table.table.table-striped.col-xs-10
        %caption Products
        %tr
          %th ID
          %th Name
          %th Price
          %th Description
          %th Photo
        - @products.each do |p|
          %tr
            %td= p.id
            %td= link_to p.name, company_product_path(@company, p)
            %td= p.price
            %td= p.description
            %td= image_tag p.picture.thumb.url, class: "img-thumbnail"
    .row
      .center= will_paginate @products, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 1

app/views/products/new.html.haml
.container
  .row
    .col-xs-offset-4.col-xs-4
      %h1.form-name New Product
      =form_for @product, url: {action: "create"} do |f|
        =f.text_field :company_id, {type: "hidden", value: params[:company_id]}
        .form-group
          %label Product name:
          = f.text_field :name, class: "form-control"
        .form-group
          %label Price:
          = f.text_field :price, class: "form-control"
        .form-group
          %label Product description:
          = f.text_area  :description, class: "form-control"
        .form-group
          %label Photo
          = f.file_field :picture
        = f.submit "Save", class: "btn btn-primary"
        = link_to "Cancel",  company_path(params[:company_id]), class: "btn btn-danger"

app/views/products/show.html.haml
.container
  .row
    .col-xs-2
    .col-xs-8
      %blockquote
        .row
          .col-xs-8
            %h1= @product.name
            %h3= "ID: #{@product.id}"
            %h3= "Price: #{@product.price}"
            %h3= "Description: #{@product.description}"
            .btn-group
              = link_to "Edit product", edit_company_product_path, class: "btn btn-default"
              = link_to "Delete product", company_product_path, method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-default"
              = link_to "Go to all products", company_path(params[:company_id]), class: "btn btn-default"
          .col-xs-4
            = image_tag @product.picture.url, class: "img-thumbnail"
    .col-xs-2